# Generated by Django 5.0.6 on 2024-06-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionID', models.IntegerField()),
                ('highway', models.IntegerField()),
                ('section', models.IntegerField()),
                ('sectionLength', models.FloatField()),
                ('sectionDescription', models.TextField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('group', models.TextField()),
                ('type', models.TextField()),
                ('county', models.TextField()),
                ('ptrucks', models.FloatField()),
                ('adt', models.IntegerField()),
                ('direction', models.TextField()),
            ],
        ),
    ]
