# Generated by Django 5.0.6 on 2024-07-11 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sectionID', models.IntegerField()),
                ('highway', models.IntegerField()),
                ('section', models.IntegerField()),
                ('sectionLength', models.FloatField()),
                ('sectionDescription', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('adt', models.IntegerField()),
                ('direction', models.CharField(max_length=255)),
            ],
        ),
    ]
