# Generated by Django 5.0.6 on 2024-06-14 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficdata',
            name='county',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='direction',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='ptrucks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='sectionDescription',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='sectionLength',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
