# Generated by Django 5.0.6 on 2024-06-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_data_app', '0002_alter_trafficdata_county_alter_trafficdata_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficdata',
            name='ptrucks',
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='sectionLength',
            field=models.FloatField(),
        ),
    ]
